"""adicionando coluna aparelho em Consumo

Revision ID: 0afd65b9251d
Revises: 93138426f91c
Create Date: 2025-02-08 19:37:52.742596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0afd65b9251d'
down_revision = '93138426f91c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aparelho', sa.String(length=80), nullable=False))
        batch_op.drop_column('tariff')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tariff', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('aparelho')

    # ### end Alembic commands ###
